run_name: 'crossdocked_full_cond'
logdir: '/home/data/zou/MSMG/diffphar/results/logdir/'
wandb_params:
  mode: 'disabled'  # disabled, offline, online
  entity: 'my_wandb_entity'
dataset: 'crossdock_full'
datadir: '/home/data/zou/MSMG/diffphar/data/processed_crossdock_noH_full_temp/'
enable_progress_bar: TRUE
num_sanity_val_steps: 0

mode: 'pocket_conditioning'  # joint, pocket_conditioning, SimpleConditionalDDPM
pocket_representation: 'full-atom' # full-atom, CA
batch_size: 4 # 32
lr: 1.0e-4
n_epochs: 1000
num_workers: 10
gpus: 1
clip_grad: True
augment_rotation: False
augment_noise: 0

egnn_params:
  device: 'cuda'
  edge_cutoff: 6.0
  joint_nf: 32
  hidden_nf: 256
  n_layers: 5
  attention: True
  tanh: True
  norm_constant: 1
  inv_sublayers: 1
  sin_embedding: False
  aggregation_method: 'sum'
  normalization_factor: 100  # used if aggregation_method='sum'

diffusion_params:
  diffusion_steps: 500
  diffusion_noise_schedule: 'polynomial_2'
  diffusion_noise_precision: 1.0e-5
  diffusion_loss_type: 'l2'
  normalize_factors: [1, 4]  # [x, h]

eval_epochs: 50
eval_params:
  n_eval_samples: 100
  eval_batch_size: 100
